### ISSUE TITLE
Sensor försvunnit senaste uppdatering

### ISSUE THREAD

**Issue by uppling** [linsvensson/sensor.greenely#53]
Hej, uppdaterade precis till senaste greenley. Nu har jag bara sensor greenley prices kvar. 

Nån annan med samma problem?

**Comment by linsvensson** [comment]
Har du kollat om något skrivs ut i loggen? Testa gärna [detta](https://github.com/linsvensson/sensor.greenely?tab=readme-ov-file#debug-logging).

**Comment by uppling** [comment]
La nyss in debug koden i configen och starta om. Inget i loggen ännu.

![klipp1](https://github.com/linsvensson/sensor.greenely/assets/118082927/df344f19-8d5f-4939-8615-c6bdd69fd22e)
![klipp2](https://github.com/linsvensson/sensor.greenely/assets/118082927/589cb3fa-f2a5-4d83-a0c6-ad744b7cf6be)

**Comment by uppling** [comment]
Nu kom det:

greenely: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 707, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1295, in async_device_update
    await hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/greenely/sensor.py", line 284, in update
    if self._api.check_auth():
       ^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/greenely/api.py", line 89, in check_auth
    if self.login() == False:
       ^^^^^^^^^^^^
  File "/config/custom_components/greenely/api.py", line 106, in login
    self.get_facility_id()
  File "/config/custom_components/greenely/api.py", line 73, in get_facility_id
    facility = next((f for f in data if f['is_primary'] == True), None)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/greenely/api.py", line 73, in <genexpr>
    facility = next((f for f in data if f['is_primary'] == True), None)
                                        ~^^^^^^^^^^^^^^
TypeError: string indices must be integers, not 'str'

**Comment by linsvensson** [comment]
Tack! Släppte precis en update nu så det ska vara fixat.

**Comment by uppling** [comment]
Tack själv, nu fungerar det igen :)
